GET http://localhost:1001/persons/default

###
GET http://localhost:1001/notes/default

###
POST http://localhost:1010/persons
Content-Type: application/json

{
  "firstName": "Sveta",
  "lastName": "Svetikova"
}

###
GET http://localhost:1010/persons
Content-Type: application/json

###
POST http://localhost:1011/notes
Content-Type: application/json

{
  "body": "Notation for Sveta else",
  "personId": "3"
}

###
GET http://localhost:1011/notes