GET http://localhost:1001/persons/default

###
GET http://localhost:1001/notes/default

###
POST http://localhost:1010/persons
Content-Type: application/json

{
  "firstName": "Alex",
  "lastName": "Plohoy"
}

###
GET http://localhost:1010/persons

###
POST http://localhost:1011/notes
Content-Type: application/json

{
  "body": "Notation",
  "personId": "3"
}

###
GET http://localhost:1011/notes