#spring:
#  application:
#    name: note-service
#  config:
#    import: configserver:http://localhost:1001

resilience4j:
  circuitbreaker:
    instances:
      person-service:
        minimumNumberOfCalls: 3
feign:
  circuitbreaker:
    enabled: true